#ifndef SSSP_CONFIG_CUH
#define SSSP_CONFIG_CUH

#define CONFIG_THREAD_GROUP_NUM 10
#define CONFIG_THREAD_NUM 256
#define CONFIG_CHUNK_SIZE 256
#define CONFIG_BATCH_SIZE 512
#define CONFIG_BATCH_SIZE_LOG 9

#endif
